dungeons:
  testdungeon:
    type: DecayDungeon
    spawnX: 2
    spawnY: 2
    spawnZ: 2
    exitX: 0
    exitY: 128
    exitZ: 0
    maxX: 100
    maxY: 64
    maxZ: 100
    exitWorld: world
    breakTimeVarianceSeconds: 10
    breakAvgTimeSeconds: 10
  persistantexample:
    type: PersistentDungeon
    spawnX: 5
    spawnY: 2
    spawnZ: 7
    exitX: 0
    exitY: 128
    exitZ: 0
    maxX: 18
    maxY: 9
    maxZ: 9
    exitWorld: world_the_end
    generateBedrockBox: false

portals:
  testdungeon1:
    type: BlockInteract
    entryOrExit: entry
    rightclick: false
    leftclick: true
    material: STONE
    cancelEvent: true
    x1: 0
    y1: 32
    z1: 0
    x2: 16
    y2: 48
    z2: 16
    world: world
    dungeon: testdungeon