name: DungeonMod
version: @version@-@apiversion@
description: Adds functionality for creating dungeons where blocks placed will disapear after time.
authors: [Amelorate]
website: https://github.com/CivWizardry/DungeonMod
depend: [WorldEdit]

main: pw.amel.dungeonmod.DungeonMod
